[theme]
base = "dark"
primaryColor = "#FFFFFF"
backgroundColor = "#0D0D0D"
secondaryBackgroundColor = "#1A1A1A"
textColor = "#F0F0F0"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
